{% set name = "hide_code" %}
{% set version = "0.5.2" %}
{% set sha256 = "aca56b3554169e7dfecedaefd790a29a2b26a6982e3557774ade387aec112423" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/h/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 1000
    skip: True  # [win or osx]
    script: |
        set -ex
        python setup.py install --single-version-externally-managed --record record.txt
        jupyter nbextension install --py hide_code --sys-prefix

requirements:
    build:
        - python
        - setuptools
        - notebook >=4.4.1
        - python-pdfkit
    run:
        - python
        - notebook >=4.4.1
        - python-pdfkit

test:
    imports:
        - hide_code

about:
    home: https://github.com/kirbs-/hide_code
    license: MIT
    license_file: hide_code/LICENSE.txt
    summary: 'Code, prompt and output hiding for Jupyter/IPython notebooks.'

extra:
  recipe-maintainers:
    - scopatz
