travis:
  secure:
    BINSTAR_TOKEN: lGy9mIwIvTdKu8lHsxJFWtiq7ZiAacyKIA0eDXhFtw+i0Raa8shQr5I/xaRB5cRqiqfSPgqLRxbG0e+9m6/PVwLy6+SXN5LhMZp1boy+yUOFnh5CkUOx4o5HFlmh+H1njuLyzX3FFfE4eurqr+W5bw1E4L3nSrBuiKxoMcOEe4ujfAKJiXqgLBkMdUEYZPrGtBy5Uk8gNz7CnTubCoZU8CUgKUK3PZkzipPtDcoznm0W3sWEzLTw+ucvX8z6hmoPFu8XdU7tebAV0rUvGy9rwhDoimFfgnGRpDwWIunaAcP3ZsuvuDDhEaAq/bZm4dy9gHW/4NRcBb40ckrYu6c3FCRSRdln7ydwn6AeXZ3yFf5RtEJCdHk9cnnlltqR4wyKhhvTos0OrPqHxArWsr/wOOiRmWIZGAoTu467vNR3Y59nrNeOoKA+eYZfrIf8qWaTI/G3cJywfVeY3/rDeUfocnlkG+/wAfAYYcTHadK4lDZlvDpyE+Vdp6gK97nu6oG0U+KhNbVFb5ZNaOiYibcv/vblgJtcha8j7uQfKrwAXai+7XPWMaTgnDJ39PAjs3uFGW2REF/TYrO3SxDB6ar/GnebpU/xx0x7z54ub6eyTR3CWT0t4Vz01Ln51P/9pCP6+xFU8oQTYWMjrDCTz2xueaD/HSXL8AK+u0uon6GiduY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
